M48
; DRILL file {KiCad 7.0.1} date Sun Sep  3 17:39:18 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-03T17:39:18-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0374
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0388
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0389
%
G90
G05
T1
X0.5213Y-0.4502
X1.2489Y-0.4502
T2
X0.0857Y-0.0431
X0.0857Y-0.1231
T3
X0.2857Y-0.0831
T0
M30
